#!/bin/bash

# Setup script for Cloudflare Pages secrets
echo "🔧 Setting up Cloudflare Pages secrets for LearningLab"
echo ""
echo "To set up your OpenAI API key as a secret:"
echo ""
echo "1. Via Command Line (recommended):"
echo "   wrangler pages secret put OPENAI_API_KEY --project-name=learninglab-nextjs"
echo ""
echo "2. Via Cloudflare Dashboard:"
echo "   - Go to https://dash.cloudflare.com"
echo "   - Navigate to Pages > learninglab-nextjs > Settings > Environment variables"
echo "   - Click 'Add variable'"
echo "   - Set Variable name: OPENAI_API_KEY"
echo "   - Set Value: your_openai_api_key_here"
echo "   - Check 'Encrypt' to make it a secret"
echo "   - Click 'Save'"
echo ""
echo "3. Deploy the changes:"
echo "   npm run pages:build && wrangler pages deploy .vercel/output/static --project-name=learninglab-nextjs --commit-dirty=true"
echo ""
echo "Note: Secrets are encrypted and cannot be viewed after setting, only overwritten."