name = "learninglab-nextjs"
compatibility_date = "2024-11-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Environment variables - default for development
[vars]
# OpenAI API key will be set via Cloudflare Pages environment variables
# Do not commit API keys to the repository for security

# Production environment variables
[env.production.vars]
# OpenAI API key will be set via Cloudflare Pages environment variables
# Do not commit API keys to the repository for security
# Updated: 2025-05-23 - Trigger new deployment
