name = "learninglab-nextjs"
compatibility_date = "2024-11-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Note: Sensitive data like API keys should be managed via Cloudflare Pages dashboard as secrets
# Regular environment variables can be set here, but secrets must be configured via:
# 1. Cloudflare Dashboard > Pages > Your Project > Settings > Environment Variables
# 2. Or via `wrangler pages secret put` command

# Non-sensitive environment variables
[vars]
NODE_ENV = "production"
APP_NAME = "LearningLab"

# Production environment variables (non-sensitive only)
[env.production.vars]
NODE_ENV = "production"
APP_NAME = "LearningLab"
