name = "learninglab-nextjs"
compatibility_date = "2024-11-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Environment variables (set these in Cloudflare dashboard)
# OPENAI_API_KEY = "your-openai-api-key"
