# Cloudflare Pages configuration
name = "learninglab"
compatibility_date = "2023-12-01"

[build]
command = "npm run build:client"
publish = "server/client/dist"

[env.production.vars]
NODE_ENV = "production"

# Environment variables are managed in Cloudflare Pages Dashboard
# Go to: Cloudflare Pages → LearningLab → Settings → Environment Variables
# Required variables:
# - OPENAI_API_KEY: Your OpenAI API key (starts with sk-proj-...)

[[env.production.kv_namespaces]]
# Add KV namespaces if needed in the future
